# Site settings
title: Fore Left
email: ryan@bridgefl.com
description: > # this means to ignore newlines until "baseurl:"
  We love golf and we tell our stories through pictures and blog posts. Come join us. A golf blog. Some of it serious, must of it trying to be funnt.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
